// GitHub Fix Applier - Phase 2 Automation
// See 11-phase2-automation.md for full specification

import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';
import type { FileChange, FixCommand, CascadeRisk } from '../types';

export type ApplyFixParams = {
  owner: string;
  repo: string;
  branch: string;
  commitSha: string;
  fixCommands: FixCommand[];
  fileChanges: FileChange[];
  commitMessage: string;
  suggestedTag: string;
  mode: 'auto' | 'pr';
  rootCause?: string;
  cascadeWarnings?: CascadeRisk[];
  sessionId?: string;
};

export type ApplyFixResult = {
  mode: 'auto' | 'pr';
  tag?: string;
  pr_url?: string;
};

export async function applyFixToGitHub(
  params: ApplyFixParams
): Promise<ApplyFixResult> {
  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: process.env.GITHUB_APP_PRIVATE_KEY,
      installationId: process.env.GITHUB_INSTALLATION_ID,
    },
  });

  const {
    owner,
    repo,
    branch,
    commitSha,
    fileChanges,
    commitMessage,
    suggestedTag,
    mode,
  } = params;

  if (mode === 'auto') {
    // Write each changed file directly to the branch
    for (const change of fileChanges) {
      const existing = await octokit.repos
        .getContent({ owner, repo, path: change.path, ref: branch })
        .catch(() => null);

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: change.path,
        message: commitMessage,
        content: Buffer.from(change.content).toString('base64'),
        sha: (existing?.data as any)?.sha,
        branch,
      });
    }

    // Create version tag
    await octokit.git.createTag({
      owner,
      repo,
      tag: suggestedTag,
      message: `Automated DebugBOB fix — ${commitMessage.split('\n')[0]}`,
      object: commitSha,
      type: 'commit',
    });
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/tags/${suggestedTag}`,
      sha: commitSha,
    });

    return { mode: 'auto', tag: suggestedTag };
  } else {
    // PR mode: create new branch, apply changes, open PR
    const fixBranch = `debugbob/fix-${Date.now()}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${fixBranch}`,
      sha: commitSha,
    });

    for (const change of fileChanges) {
      const existing = await octokit.repos
        .getContent({ owner, repo, path: change.path, ref: fixBranch })
        .catch(() => null);

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: change.path,
        message: commitMessage,
        content: Buffer.from(change.content).toString('base64'),
        sha: (existing?.data as any)?.sha,
        branch: fixBranch,
      });
    }

    const pr = await octokit.pulls.create({
      owner,
      repo,
      title: commitMessage.split('\n')[0],
      body: formatPRBody(params),
      head: fixBranch,
      base: branch,
    });

    return { mode: 'pr', pr_url: pr.data.html_url, tag: suggestedTag };
  }
}

function formatPRBody(params: ApplyFixParams): string {
  return [
    '## 🤖 DebugBOB Automated Fix',
    '',
    '### Root Cause',
    params.rootCause ?? '(see pipeline analysis)',
    '',
    '### Fix Applied',
    params.fixCommands
      .map((c) => `- \`${c.command}\` — ${c.explanation}`)
      .join('\n'),
    '',
    '### Cascade Risks',
    params.cascadeWarnings?.length
      ? params.cascadeWarnings
          .map(
            (r) =>
              `- ⚠️ **${r.severity}**: ${r.description} — ${r.prevention}`
          )
          .join('\n')
      : 'None detected.',
    '',
    `### Version Tag`,
    `This fix will be tagged \`${params.suggestedTag}\` after merge.`,
    '',
    `_Generated by DebugBOB — [view full analysis](${process.env.NEXT_PUBLIC_APP_URL}/session/${params.sessionId})_`,
  ].join('\n');
}

// Made with Bob
